function angles_threshold = get_trm_angles_threshold(...
    begin_pdb_path, end_pdb_path, begin_pdb_ind, ...
    end_pdb_ind, n_angles)

trmodel = trm_from_files(begin_pdb_path, end_pdb_path, ...
    begin_pdb_ind, end_pdb_ind, 0);

[~,angle_indices] = sort(abs(circdist(trmodel.psi(:,1), ...
    trmodel.psi(:,end))), 'descend');

angles_threshold = abs(circdist(...
    trmodel.psi(angle_indices(n_angles+1),1), ...
    trmodel.psi(angle_indices(n_angles+1),end)));

end

